require("recipe.diesel-fuel")
require("recipe.diesel-generator")
require("recipe.wind-turbine")
require("recipe.burner-generator")
require("recipe.coal-from-crude")
require("recipe.coal-liquefaction")